"""empty message

Revision ID: 0648ea352c87
Revises: 44a11ca3db02
Create Date: 2022-10-09 20:41:23.221011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0648ea352c87'
down_revision = '44a11ca3db02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thesis', 'adviser_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thesis', 'adviser_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
    # ### end Alembic commands ###
