"""empty message

Revision ID: 29beba3a0c4f
Revises: a010baf71314
Create Date: 2021-08-13 23:39:47.813762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29beba3a0c4f'
down_revision = 'a010baf71314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quantitative_criteria_ibfk_1', 'quantitative_criteria', type_='foreignkey')
    op.create_foreign_key(None, 'quantitative_criteria', 'quantitative_rating', ['quantitative_rating_id'], ['id'], ondelete='cascade')
    op.drop_constraint('quantitative_criteria_grade_ibfk_1', 'quantitative_criteria_grade', type_='foreignkey')
    op.drop_constraint('quantitative_criteria_grade_ibfk_2', 'quantitative_criteria_grade', type_='foreignkey')
    op.create_foreign_key(None, 'quantitative_criteria_grade', 'quantitative_criteria', ['quantitative_criteria_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'quantitative_criteria_grade', 'quantitative_panelist_grade', ['quantitative_panelist_grade_id'], ['id'], ondelete='cascade')
    op.drop_constraint('quantitative_panelist_grade_ibfk_2', 'quantitative_panelist_grade', type_='foreignkey')
    op.drop_constraint('quantitative_panelist_grade_ibfk_1', 'quantitative_panelist_grade', type_='foreignkey')
    op.create_foreign_key(None, 'quantitative_panelist_grade', 'user', ['panelist_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'quantitative_panelist_grade', 'thesis', ['thesis_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quantitative_panelist_grade', type_='foreignkey')
    op.drop_constraint(None, 'quantitative_panelist_grade', type_='foreignkey')
    op.create_foreign_key('quantitative_panelist_grade_ibfk_1', 'quantitative_panelist_grade', 'user', ['panelist_id'], ['id'])
    op.create_foreign_key('quantitative_panelist_grade_ibfk_2', 'quantitative_panelist_grade', 'thesis', ['thesis_id'], ['id'])
    op.drop_constraint(None, 'quantitative_criteria_grade', type_='foreignkey')
    op.drop_constraint(None, 'quantitative_criteria_grade', type_='foreignkey')
    op.create_foreign_key('quantitative_criteria_grade_ibfk_2', 'quantitative_criteria_grade', 'quantitative_panelist_grade', ['quantitative_panelist_grade_id'], ['id'])
    op.create_foreign_key('quantitative_criteria_grade_ibfk_1', 'quantitative_criteria_grade', 'quantitative_criteria', ['quantitative_criteria_id'], ['id'])
    op.drop_constraint(None, 'quantitative_criteria', type_='foreignkey')
    op.create_foreign_key('quantitative_criteria_ibfk_1', 'quantitative_criteria', 'quantitative_rating', ['quantitative_rating_id'], ['id'])
    # ### end Alembic commands ###
