"""empty message

Revision ID: 2a0be38daf8a
Revises: e0b60583e0be
Create Date: 2021-07-14 21:23:21.259434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0be38daf8a'
down_revision = 'e0b60583e0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_student', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_student')
    # ### end Alembic commands ###
