"""empty message

Revision ID: 365e6c958241
Revises: 99629ad6532f
Create Date: 2021-06-21 17:38:17.989730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365e6c958241'
down_revision = '99629ad6532f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='thesis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'thesis', ['title'], unique=False)
    # ### end Alembic commands ###
