"""empty message

Revision ID: 3e56758c3859
Revises: 7e9a5a38cd51
Create Date: 2021-06-19 22:13:54.961305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e56758c3859'
down_revision = '7e9a5a38cd51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'description',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'description',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###
