"""empty message

Revision ID: 44a11ca3db02
Revises: edb497878e58
Create Date: 2021-11-02 17:55:53.552562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44a11ca3db02'
down_revision = 'edb497878e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quantitative_criteria_rating',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('rate', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantitative_criteria_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['quantitative_criteria_id'], ['quantitative_criteria.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('quantitative_criteria', sa.Column('description', sa.String(length=500), nullable=True))
    op.alter_column('quantitative_criteria', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quantitative_criteria', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_column('quantitative_criteria', 'description')
    op.drop_table('quantitative_criteria_rating')
    # ### end Alembic commands ###
