"""empty message

Revision ID: 54699bbef92e
Revises: 101d766f33b2
Create Date: 2021-08-08 18:28:48.478516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54699bbef92e'
down_revision = '101d766f33b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('individual_rating_ibfk_2', 'individual_rating', type_='foreignkey')
    op.drop_constraint('individual_rating_ibfk_1', 'individual_rating', type_='foreignkey')
    op.drop_column('individual_rating', 'student_id')
    op.drop_column('individual_rating', 'panelist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_rating', sa.Column('panelist_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False))
    op.add_column('individual_rating', sa.Column('student_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False))
    op.create_foreign_key('individual_rating_ibfk_1', 'individual_rating', 'user', ['panelist_id'], ['id'])
    op.create_foreign_key('individual_rating_ibfk_2', 'individual_rating', 'user', ['student_id'], ['id'])
    # ### end Alembic commands ###
