"""empty message

Revision ID: 7e9a5a38cd51
Revises: ca36e7f6ed2a
Create Date: 2021-06-19 22:07:27.536249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e9a5a38cd51'
down_revision = 'ca36e7f6ed2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(display_width=10, unsigned=True),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
