"""empty message

Revision ID: 90979d9abcd6
Revises: 29beba3a0c4f
Create Date: 2021-10-08 09:29:22.564077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90979d9abcd6'
down_revision = '29beba3a0c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thesis', sa.Column('proposal_form', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'thesis', ['proposal_form'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thesis', type_='unique')
    op.drop_column('thesis', 'proposal_form')
    # ### end Alembic commands ###
