"""empty message

Revision ID: 96ba8b1e0a40
Revises: 3e42f75d5a50
Create Date: 2021-08-07 21:33:22.517299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96ba8b1e0a40'
down_revision = '3e42f75d5a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_rating',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('intelligent_response', sa.Integer(), nullable=True),
    sa.Column('respectful_response', sa.Integer(), nullable=True),
    sa.Column('communication_skills', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('attire', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), nullable=False),
    sa.Column('student_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('panelist_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['panelist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_list',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('comment', sa.String(length=10000), nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), nullable=False),
    sa.Column('thesis_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('panelist_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['panelist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revision_list')
    op.drop_table('individual_rating')
    # ### end Alembic commands ###
