"""empty message

Revision ID: a010baf71314
Revises: b0e6985ff0db
Create Date: 2021-08-09 21:18:53.952293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a010baf71314'
down_revision = 'b0e6985ff0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'quantitative_rating', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quantitative_rating', type_='unique')
    # ### end Alembic commands ###
