"""empty message

Revision ID: a1beaaabf08e
Revises: e9681f964742
Create Date: 2021-07-05 17:09:52.508849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1beaaabf08e'
down_revision = 'e9681f964742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('log_ibfk_1', 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key('log_ibfk_1', 'log', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
