"""empty message

Revision ID: ae44d4d75295
Revises: 96ba8b1e0a40
Create Date: 2021-08-07 21:36:41.497963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae44d4d75295'
down_revision = '96ba8b1e0a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_rating', sa.Column('thesis_id', mysql.INTEGER(unsigned=True), nullable=False))
    op.create_foreign_key(None, 'individual_rating', 'thesis', ['thesis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'individual_rating', type_='foreignkey')
    op.drop_column('individual_rating', 'thesis_id')
    # ### end Alembic commands ###
