"""empty message

Revision ID: bd024a4fc0f8
Revises: d07c74a1204e
Create Date: 2021-10-21 20:36:21.484240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd024a4fc0f8'
down_revision = 'd07c74a1204e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quantitative_rating', sa.Column('max_grade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quantitative_rating', 'max_grade')
    # ### end Alembic commands ###
