"""empty message

Revision ID: ca36e7f6ed2a
Revises: 5c987e809e7f
Create Date: 2021-06-19 21:58:11.362541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca36e7f6ed2a'
down_revision = '5c987e809e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
