"""empty message

Revision ID: d07c74a1204e
Revises: 90979d9abcd6
Create Date: 2021-10-09 20:54:47.014013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07c74a1204e'
down_revision = '90979d9abcd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('individual_rating_ibfk_5', 'individual_rating', type_='foreignkey')
    op.drop_constraint('individual_rating_ibfk_3', 'individual_rating', type_='foreignkey')
    op.drop_constraint('individual_rating_ibfk_4', 'individual_rating', type_='foreignkey')
    op.create_foreign_key(None, 'individual_rating', 'user', ['panelist_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'individual_rating', 'thesis', ['thesis_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'individual_rating', 'user', ['student_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'individual_rating', type_='foreignkey')
    op.drop_constraint(None, 'individual_rating', type_='foreignkey')
    op.drop_constraint(None, 'individual_rating', type_='foreignkey')
    op.create_foreign_key('individual_rating_ibfk_4', 'individual_rating', 'user', ['panelist_id'], ['id'])
    op.create_foreign_key('individual_rating_ibfk_3', 'individual_rating', 'thesis', ['thesis_id'], ['id'])
    op.create_foreign_key('individual_rating_ibfk_5', 'individual_rating', 'user', ['student_id'], ['id'])
    # ### end Alembic commands ###
