"""empty message

Revision ID: e0b60583e0be
Revises: a1beaaabf08e
Create Date: 2021-07-05 17:12:38.802539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b60583e0be'
down_revision = 'a1beaaabf08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('log_ibfk_1', 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key('log_ibfk_1', 'log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
