"""empty message

Revision ID: e15660c2e49f
Revises: 88ad10de0594
Create Date: 2021-06-22 15:48:30.711512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e15660c2e49f'
down_revision = '88ad10de0594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thesis', 'overview',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thesis', 'overview',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
