"""empty message

Revision ID: e2f7e477718e
Revises: f7f068394633
Create Date: 2021-07-26 22:05:22.655453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f7e477718e'
down_revision = 'f7f068394633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thesis', sa.Column('presentor_number', sa.Integer(), nullable=True))
    op.drop_constraint('thesis_ibfk_4', 'thesis', type_='foreignkey')
    op.create_foreign_key(None, 'thesis', 'group', ['group_id'], ['id'])
    op.add_column('user', sa.Column('is_guest_panelist', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_guest_panelist')
    op.drop_constraint(None, 'thesis', type_='foreignkey')
    op.create_foreign_key('thesis_ibfk_4', 'thesis', 'thesis', ['group_id'], ['id'])
    op.drop_column('thesis', 'presentor_number')
    # ### end Alembic commands ###
