"""empty message

Revision ID: e9681f964742
Revises: e15660c2e49f
Create Date: 2021-06-22 16:11:42.919460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9681f964742'
down_revision = 'e15660c2e49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thesis', 'keywords',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thesis', 'keywords',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
