"""empty message

Revision ID: edb497878e58
Revises: bd024a4fc0f8
Create Date: 2021-10-26 18:35:35.208463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edb497878e58'
down_revision = 'bd024a4fc0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thesis', sa.Column('quantitative_rating_developed_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'thesis', 'quantitative_rating', ['quantitative_rating_developed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thesis', type_='foreignkey')
    op.drop_column('thesis', 'quantitative_rating_developed_id')
    # ### end Alembic commands ###
