"""empty message

Revision ID: f7f068394633
Revises: 40c2bf2748e7
Create Date: 2021-07-26 19:25:38.011334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7f068394633'
down_revision = '40c2bf2748e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('chairmain_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['chairmain_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('panelists',
    sa.Column('group_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('thesis', sa.Column('group_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.add_column('thesis', sa.Column('presentor_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thesis', 'thesis', ['group_id'], ['id'])
    op.add_column('user', sa.Column('is_guest_panelist', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_guest_panelist')
    op.drop_constraint(None, 'thesis', type_='foreignkey')
    op.drop_column('thesis', 'presentor_number')
    op.drop_column('thesis', 'group_id')
    op.drop_table('panelists')
    op.drop_table('group')
    # ### end Alembic commands ###
